//我的订单 table
$(function(){
$(".choice-left-title ul li a").click(function () {
                $(".choice-left-title ul li a").each(function () {
                    $(this).removeClass("current");
                });
                $(this).addClass("current");
            });
$('.choice-left-title ul li a').click(function(){
  var index=$('.choice-left-title ul li a').index(this);
     if(index==0){
     $('#citi-tab1').show();
  	 $('#citi-tab2').hide();
  	 $('#citi-tab3').hide();
  	 $('#citi-tab4').hide();
   }
   if(index==1){
     $('#citi-tab2').show();
  	 $('#citi-tab1').hide();
  	 $('#citi-tab3').hide();
  	 $('#citi-tab4').hide();
   }
   if(index==2){
     $('#citi-tab3').show();
  	 $('#citi-tab2').hide();
  	 $('#citi-tab1').hide();
  	 $('#citi-tab4').hide();
   }
   if(index==3){
     $('#citi-tab4').show();
  	 $('#citi-tab2').hide();
  	 $('#citi-tab3').hide();
  	 $('#citi-tab1').hide();
   }
  }); 
});
//第一个
$(function(){
$("#city-one ul li a").click(function () {
                $("#city-one ul li a").each(function () {
                    $(this).removeClass("current");
                });
                $(this).addClass("current");
            });
$('#city-one ul li a').click(function(){
  var index=$('#city-one ul li a').index(this);
     if(index==0){
     $('#province1').show();
  	 $('#province2').hide();
  	 $('#province3').hide();
  	 $('#province4').hide();
  	 $('#province5').hide();
  	 $('#province6').hide();
  	 $('#province7').hide();
  	 $('#province8').hide();
   }
   if(index==1){
     $('#province2').show();
  	 $('#province1').hide();
  	 $('#province3').hide();
  	 $('#province4').hide();
  	 $('#province5').hide();
  	 $('#province6').hide();
  	 $('#province7').hide();
  	 $('#province8').hide();
   }
   if(index==2){
     $('#province3').show();
  	 $('#province2').hide();
  	 $('#province1').hide();
  	 $('#province4').hide();
  	 $('#province5').hide();
  	 $('#province6').hide();
  	 $('#province7').hide();
  	 $('#province8').hide();
   }
   if(index==3){
     $('#province4').show();
  	 $('#province3').hide();
  	 $('#province2').hide();
  	 $('#province1').hide();
  	 $('#province5').hide();
  	 $('#province6').hide();
  	 $('#province7').hide();
  	 $('#province8').hide();
   }
   if(index==4){
     $('#province5').show();
  	 $('#province3').hide();
  	 $('#province2').hide();
  	 $('#province1').hide();
  	 $('#province4').hide();
  	 $('#province6').hide();
  	 $('#province7').hide();
  	 $('#province8').hide();
   }
   if(index==5){
     $('#province6').show();
  	 $('#province3').hide();
  	 $('#province2').hide();
  	 $('#province1').hide();
  	 $('#province4').hide();
  	 $('#province5').hide();
  	 $('#province7').hide();
  	 $('#province8').hide();
   }
    if(index==6){
     $('#province7').show();
  	 $('#province3').hide();
  	 $('#province2').hide();
  	 $('#province1').hide();
  	 $('#province4').hide();
  	 $('#province5').hide();
  	 $('#province6').hide();
  	 $('#province8').hide();
   }
    if(index==7){
     $('#province8').show();
  	 $('#province3').hide();
  	 $('#province2').hide();
  	 $('#province1').hide();
  	 $('#province4').hide();
  	 $('#province5').hide();
  	 $('#province6').hide();
  	 $('#province7').hide();
   }
  }); 
});
//我的订单 table
$(function(){
$(".eject-choice-left-title ul li a").click(function () {
                $(".eject-choice-left-title ul li a").each(function () {
                    $(this).removeClass("current");
                });
                $(this).addClass("current");
            });
$('.eject-choice-left-title ul li a').click(function(){
  var index=$('.eject-choice-left-title ul li a').index(this);
     if(index==0){
     $('#eject-citi-tab1').show();
  	 $('#eject-citi-tab2').hide();
  	 $('#eject-citi-tab3').hide();
  	 $('#eject-citi-tab4').hide();
   }
   if(index==1){
     $('#eject-citi-tab2').show();
  	 $('#eject-citi-tab1').hide();
  	 $('#eject-citi-tab3').hide();
  	 $('#eject-citi-tab4').hide();
   }
   if(index==2){
     $('#eject-citi-tab3').show();
  	 $('#eject-citi-tab2').hide();
  	 $('#eject-citi-tab1').hide();
  	 $('#eject-citi-tab4').hide();
   }
   if(index==3){
     $('#eject-citi-tab4').show();
  	 $('#eject-citi-tab2').hide();
  	 $('#eject-citi-tab3').hide();
  	 $('#eject-citi-tab1').hide();
   }
  }); 
});
//第一个
$(function(){
$("#city-tow ul li a").click(function () {
                $("#city-tow ul li a").each(function () {
                    $(this).removeClass("current");
                });
                $(this).addClass("current");
            });
$('#city-tow ul li a').click(function(){
  var index=$('#city-tow ul li a').index(this);
     if(index==0){
     $('#eject-province1').show();
  	 $('#eject-province2').hide();
  	 $('#eject-province3').hide();
  	 $('#eject-province4').hide();
  	 $('#eject-province5').hide();
  	 $('#eject-province6').hide();
  	 $('#eject-province7').hide();
  	 $('#eject-province8').hide();
   }
   if(index==1){
     $('#eject-province2').show();
  	 $('#eject-province1').hide();
  	 $('#eject-province3').hide();
  	 $('#eject-province4').hide();
  	 $('#eject-province5').hide();
  	 $('#eject-province6').hide();
  	 $('#eject-province7').hide();
  	 $('#eject-province8').hide();
   }
   if(index==2){
     $('#eject-province3').show();
  	 $('#eject-province2').hide();
  	 $('#eject-province1').hide();
  	 $('#eject-province4').hide();
  	 $('#eject-province5').hide();
  	 $('#eject-province6').hide();
  	 $('#eject-province7').hide();
  	 $('#eject-province8').hide();
   }
   if(index==3){
     $('#eject-province4').show();
  	 $('#eject-province3').hide();
  	 $('#eject-province2').hide();
  	 $('#eject-province1').hide();
  	 $('#eject-province5').hide();
  	 $('#eject-province6').hide();
  	 $('#eject-province7').hide();
  	 $('#eject-province8').hide();
   }
   if(index==4){
     $('#eject-province5').show();
  	 $('#eject-province3').hide();
  	 $('#eject-province2').hide();
  	 $('#eject-province1').hide();
  	 $('#eject-province4').hide();
  	 $('#eject-province6').hide();
  	 $('#eject-province7').hide();
  	 $('#eject-province8').hide();
   }
   if(index==5){
     $('#eject-province6').show();
  	 $('#eject-province3').hide();
  	 $('#eject-province2').hide();
  	 $('#eject-province1').hide();
  	 $('#eject-province4').hide();
  	 $('#eject-province5').hide();
  	 $('#eject-province7').hide();
  	 $('#eject-province8').hide();
   }
    if(index==6){
     $('#eject-province7').show();
  	 $('#eject-province3').hide();
  	 $('#eject-province2').hide();
  	 $('#eject-province1').hide();
  	 $('#eject-province4').hide();
  	 $('#eject-province5').hide();
  	 $('#eject-province6').hide();
  	 $('#eject-province8').hide();
   }
    if(index==7){
     $('#eject-province8').show();
  	 $('#eject-province3').hide();
  	 $('#eject-province2').hide();
  	 $('#eject-province1').hide();
  	 $('#eject-province4').hide();
  	 $('#eject-province5').hide();
  	 $('#eject-province6').hide();
  	 $('#eject-province7').hide();
   }
  }); 
});