//首页 
jQuery(document).ready(function($) {
	$('#modify-btn').click(function(){
	$('#eject-mask').fadeIn(100);
	$('#classification').slideDown(100);
	})
	$('#i-close').click(function(){
	$('#eject-mask').fadeOut(200);
	$('#classification').slideUp(200);
	})
	$('#eject-btn-close').click(function(){
	$('#eject-mask').fadeOut(200);
	$('#classification').slideUp(200);
	})
})
//首页 
jQuery(document).ready(function($) {
	$('#currency-btn').click(function(){
	$('#eject-mask').fadeIn(100);
	$('#currency').slideDown(100);
	})
	$('#currency-close').click(function(){
	$('#eject-mask').fadeOut(200);
	$('#currency').slideUp(200);
	})
	$('#currency-close').click(function(){
	$('#eject-mask').fadeOut(200);
	$('#currency').slideUp(200);
	})
	/*$('#medium-btn-close').click(function(){
	$('#eject-mask').fadeOut(200);
	$('#currency').slideUp(200);
	})*/
})
